# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e1253b4c6d487607b8ce35c38aa24a4769f26ddd39519c3ce257246609148b4c2ffe9d409302ab235d25f6230e5d736b86427002561cf8e96f16d6be3bd500c

test:
  secret_key_base: 10567bcec75de3378339d6278fdfad118e5758b6983d7d3b43346d92c21b8d4254d45f015c87386c54e9f6b329ceb118dcb828af13adc0c0cd35ac430474ffca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
